# Generated by Django 6.0 on 2026-01-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_profile_pic_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
