# Generated by Django 6.0 on 2026-01-25 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=80)),
                ('product_img', models.ImageField(default=None, upload_to='product/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('negotiable', models.BooleanField(default=False)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('location_override', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic_override', models.ImageField(blank=True, null=True, upload_to='product_profiles/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
